#1-3 NumPyテスト

In [0]:
import numpy as np

In [0]:
""""
#1
Write a code generating the following vector B from a given vector A. 

A:
array([9, 4, 5, 1, 8, 6])


B:
array([1, 4, 5, 6, 8, 9])
""""
A=np.array([9, 4, 5, 1, 8, 6])

def test(A):
    return np.sort(A)

print(test(A))

In [0]:
""""
#2
Write a code generating the following list of ndarray B from a given ndarray A. 
 
A:
array([[2, 5, 2, 6, 3, 2, 5, 1, 9, 4, 5, 6],
       [5, 8, 4, 9, 3, 1, 7, 9, 8, 3, 5, 8],
       [5, 1, 2, 7, 2, 1, 1, 2, 5, 4, 9, 3],
       [7, 7, 7, 9, 9, 9, 2, 5, 6, 4, 3, 8]])


B:
[array([[2, 5, 2, 6, 3, 2, 5, 1, 9, 4, 5, 6],
       [5, 8, 4, 9, 3, 1, 7, 9, 8, 3, 5, 8]]),
 array([[5, 1, 2, 7, 2, 1, 1, 2, 5, 4, 9, 3],
       [7, 7, 7, 9, 9, 9, 2, 5, 6, 4, 3, 8]])]


A's shape: (4, 12)
""""
A=np.array([[2, 5, 2, 6, 3, 2, 5, 1, 9, 4, 5, 6],
       [5, 8, 4, 9, 3, 1, 7, 9, 8, 3, 5, 8],
       [5, 1, 2, 7, 2, 1, 1, 2, 5, 4, 9, 3],
       [7, 7, 7, 9, 9, 9, 2, 5, 6, 4, 3, 8]])

def test(A):
    return np.split(A,[2])

print(test(A))

In [0]:
""""
#3
Write a code generating the following vector B from a given vector A. 
 
A:
array([3, 8, 6, 3, 9])


B:
array([3, 9, 3, 8, 6])


A's shape: (5,)    B's shape: (5,)
"""
A=np.array([3, 8, 6, 3, 9])

def test(A):
     return A[[3,4,0,1,2]]
print(test(A))

In [0]:
"""
#4
Write a code generating the following list of ndarray B from a given ndarray A. 
 
A:
array([[2, 5, 1, 4, 2, 4],
       [3, 9, 2, 3, 7, 3],
       [2, 8, 1, 8, 5, 3]])


B:
[array([[2, 5, 1],
       [3, 9, 2],
       [2, 8, 1]]),
 array([[4, 2, 4],
       [3, 7, 3],
       [8, 5, 3]])]


A's shape: (3, 6)
"""
A=np.array([[2, 5, 1, 4, 2, 4],
       [3, 9, 2, 3, 7, 3],
       [2, 8, 1, 8, 5, 3]])

def test(A):
    return np.hsplit(A,[3])

print(test(A))

In [0]:
"""
#5
 Write a code generating the following ndarray B from a given ndarray A. 

A:
array([[1, 5, 7, 7],
       [4, 9, 9, 3],
       [8, 8, 5, 6]])


B:
array([[False, False,  True,  True],
       [False,  True,  True, False],
       [ True,  True, False,  True]])


A's shape: (3, 4), B's shape: (3, 4) 

Hint: 5
"""

A=np.array([[1, 5, 7, 7],
       [4, 9, 9, 3],
       [8, 8, 5, 6]])

def test(A):
    return (A > 5)

print(test(A))

In [0]:
"""
#6
Write a code generating the following ndarray C from given ndarray A and ndarray B. 
 
A:
array([[3, 5, 0, 6, 2],
       [0, 7, 3, 5, 7],
       [1, 4, 4, 7, 5],
       [7, 0, 6, 3, 3]])


B:
array([[4, 7, 3, 4, 7],
       [3, 0, 4, 5, 5],
       [7, 3, 3, 5, 8],
       [7, 5, 6, 3, 4]])


C:
array([[3, 5, 0, 6, 2, 4, 7, 3, 4, 7],
       [0, 7, 3, 5, 7, 3, 0, 4, 5, 5],
       [1, 4, 4, 7, 5, 7, 3, 3, 5, 8],
       [7, 0, 6, 3, 3, 7, 5, 6, 3, 4]])


A's shape: (4, 5)    B's shape: (4, 5)    C's shape: (4, 10)
"""
A=np.array([[3, 5, 0, 6, 2],
       [0, 7, 3, 5, 7],
       [1, 4, 4, 7, 5],
       [7, 0, 6, 3, 3]])


B=np.array([[4, 7, 3, 4, 7],
       [3, 0, 4, 5, 5],
       [7, 3, 3, 5, 8],
       [7, 5, 6, 3, 4]])

def test(A,B):
    return np.hstack((A,B))

print(test(A,B))

In [0]:
"""
#7
Write a code generating the following ndarray C from given ndarray A and ndarray B. 
 
A:
array([[2, 3, 2],
       [2, 3, 3],
       [2, 1, 1]])


B:
array([[3, 3, 3],
       [2, 2, 1],
       [3, 1, 1]])


C:
array([[18, 14, 11],
       [21, 15, 12],
       [11,  9,  8]])


A's shape: (3, 3)    B's shape: (3, 3)    C's shape: (3, 3)
"""
A=np.array([[2, 3, 2],
       [2, 3, 3],
       [2, 1, 1]])


B=np.array([[3, 3, 3],
       [2, 2, 1],
       [3, 1, 1]])

def test(A, B):
    return np.dot(A,B)

print(test(A,B))

In [0]:
"""
#8
 Write a code generating the following ndarray B from a given ndarray A. 

A:
array([[ 3, 18,  6,  4,  3, 18,  7],
       [13, 11, 11, 19, 12, 19,  9],
       [ 2, 14,  4,  2, 18, 17, 13],
       [ 2, 15,  8,  3, 12, 13,  5],
       [ 7, 15, 13,  4, 16, 16, 10],
       [ 3, 13,  3,  4,  8, 16, 11],
       [12,  1, 14, 14,  8, 19, 13]])


B:
array([[3, 0, 6, 4, 3, 0, 7],
       [0, 0, 0, 0, 0, 0, 9],
       [2, 0, 4, 2, 0, 0, 0],
       [2, 0, 8, 3, 0, 0, 5],
       [7, 0, 0, 4, 0, 0, 0],
       [3, 0, 3, 4, 8, 0, 0],
       [0, 1, 0, 0, 8, 0, 0]])


A's shape: (7, 7), B's shape: (7, 7) 

Hint: 10
"""
A=np.array([[ 3, 18,  6,  4,  3, 18,  7],
       [13, 11, 11, 19, 12, 19,  9],
       [ 2, 14,  4,  2, 18, 17, 13],
       [ 2, 15,  8,  3, 12, 13,  5],
       [ 7, 15, 13,  4, 16, 16, 10],
       [ 3, 13,  3,  4,  8, 16, 11],
       [12,  1, 14, 14,  8, 19, 13]])

def test(A):
    return np.where(A>=10,0,A)

print(test(A))

In [0]:
"""
#9
Write a code generating the following ndarray B from a given ndarray A. 
 
A:
array([[0, 2, 5, 4, 5],
       [8, 2, 3, 8, 2],
       [3, 2, 4, 1, 8],
       [8, 0, 8, 7, 2],
       [0, 3, 8, 7, 3]])


B:
array([[16],
       [23],
       [18],
       [25],
       [21]])


A's shape: (5, 5)    B's shape: (5, 1)
"""
A=np.array([[0, 2, 5, 4, 5],
       [8, 2, 3, 8, 2],
       [3, 2, 4, 1, 8],
       [8, 0, 8, 7, 2],
       [0, 3, 8, 7, 3]])

def test(A):
    return np.sum(A,axis=1).reshape(5,1)

print(test(A))  

In [0]:
"""
#10
Write a code generating the following ndarray C from given ndarray A and ndarray B. 
 
A:
array([[90, 40, 20, 70, 60, 30, 40, 80],
       [70, 10, 90, 60, 70, 90, 80, 30],
       [30, 90, 60, 90, 90, 10, 50, 60],
       [20, 30, 30, 40, 20, 20, 90, 30],
       [10, 50, 60, 60, 10, 30, 10, 50],
       [10, 10, 90, 70, 90, 30, 90, 90],
       [30, 20, 50, 50, 20, 70, 80, 70]])


B:
array([[7, 1, 7, 7, 3, 5, 4, 3]])


C:
array([[97, 41, 27, 77, 63, 35, 44, 83],
       [77, 11, 97, 67, 73, 95, 84, 33],
       [37, 91, 67, 97, 93, 15, 54, 63],
       [27, 31, 37, 47, 23, 25, 94, 33],
       [17, 51, 67, 67, 13, 35, 14, 53],
       [17, 11, 97, 77, 93, 35, 94, 93],
       [37, 21, 57, 57, 23, 75, 84, 73]])


A's shape: (7, 8)    B's shape: (1, 8)    C's shape: (7, 8)
"""

A=np.array([[90, 40, 20, 70, 60, 30, 40, 80],
       [70, 10, 90, 60, 70, 90, 80, 30],
       [30, 90, 60, 90, 90, 10, 50, 60],
       [20, 30, 30, 40, 20, 20, 90, 30],
       [10, 50, 60, 60, 10, 30, 10, 50],
       [10, 10, 90, 70, 90, 30, 90, 90],
       [30, 20, 50, 50, 20, 70, 80, 70]])

B=np.array([[7, 1, 7, 7, 3, 5, 4, 3]])

def test(A,B):
    return A+B

print(test(A,B))

In [0]:
"""
#11
Write a code generating the following ndarray C from given vector A and vector B. 
 
A:
array([8, 0, 3, 0, 3, 0, 0, 5, 6, 8, 5, 8, 6, 3, 3])


B:
array([3, 1, 8, 4, 5, 4, 5, 5, 2, 5, 4, 0, 7, 3, 7])


C:
array([[24,  0, 24,  0, 15],
       [ 0,  0, 25, 12, 40],
       [20,  0, 42,  9, 21]])


A's shape: (15,)    B's shape: (15,)    C's shape: (3, 5)
"""
A=np.array([8, 0, 3, 0, 3, 0, 0, 5, 6, 8, 5, 8, 6, 3, 3])
B=np.array([3, 1, 8, 4, 5, 4, 5, 5, 2, 5, 4, 0, 7, 3, 7])

def test(A,B):
    return (A*B).reshape(3,5)

print(test(A,B))

In [0]:
"""
#12
Write a code generating the following ndarray C from given ndarray A and ndarray B. 
 
A:
array([[3, 2, 3],
       [3, 3, 3],
       [3, 2, 2]])


B:
array([[3, 2, 1],
       [1, 3, 2],
       [2, 2, 1]])


C:
array([[17, 18, 10],
       [18, 21, 12],
       [15, 16,  9]])


A's shape: (3, 3)    B's shape: (3, 3)    C's shape: (3, 3)
"""
A=np.array([[3, 2, 3],
       [3, 3, 3],
       [3, 2, 2]])


B=np.array([[3, 2, 1],
       [1, 3, 2],
       [2, 2, 1]])

def test(A, B):
    return np.dot(A,B)

print(test(A,B))


In [0]:
"""
#13
Write a code generating the following ndarray C from given ndarray A and ndarray B. 
 
A:
array([[2, 2, 1, 5, 2, 6],
       [6, 2, 2, 8, 4, 3],
       [8, 8, 6, 3, 6, 2],
       [3, 2, 6, 2, 6, 4],
       [7, 1, 7, 3, 6, 8],
       [2, 2, 8, 1, 3, 3]])


B:
array([[1, 3, 8, 7, 5, 1],
       [3, 3, 5, 3, 4, 2],
       [8, 1, 6, 3, 8, 1],
       [5, 8, 6, 7, 3, 1],
       [5, 3, 4, 8, 2, 5],
       [1, 7, 3, 4, 8, 2]])


C:
array([[ 2,  6,  8, 35, 10,  6],
       [18,  6, 10, 24, 16,  6],
       [64,  8, 36,  9, 48,  2],
       [15, 16, 36, 14, 18,  4],
       [35,  3, 28, 24, 12, 40],
       [ 2, 14, 24,  4, 24,  6]])


A's shape: (6, 6)    B's shape: (6, 6)    C's shape: (6, 6)
"""
A=np.array([[2, 2, 1, 5, 2, 6],
       [6, 2, 2, 8, 4, 3],
       [8, 8, 6, 3, 6, 2],
       [3, 2, 6, 2, 6, 4],
       [7, 1, 7, 3, 6, 8],
       [2, 2, 8, 1, 3, 3]])


B=np.array([[1, 3, 8, 7, 5, 1],
       [3, 3, 5, 3, 4, 2],
       [8, 1, 6, 3, 8, 1],
       [5, 8, 6, 7, 3, 1],
       [5, 3, 4, 8, 2, 5],
       [1, 7, 3, 4, 8, 2]])

def test(A,B):
    return A*B

print(test(A,B))


In [0]:
"""
#14
Write a code generating the following ndarray B from a given ndarray A. 
 
A:
array([[3, 5, 0, 6, 4, 2],
       [1, 6, 2, 5, 3, 3],
       [1, 0, 0, 2, 3, 0],
       [6, 5, 6, 4, 8, 4],
       [2, 1, 7, 4, 5, 2],
       [2, 6, 4, 6, 3, 6],
       [8, 7, 2, 0, 1, 8]])


B:
array([[8, 7, 7, 6, 8, 8]])


A's shape: (7, 6)    B's shape: (1, 6)
"""
A=np.array([[3, 5, 0, 6, 4, 2],
       [1, 6, 2, 5, 3, 3],
       [1, 0, 0, 2, 3, 0],
       [6, 5, 6, 4, 8, 4],
       [2, 1, 7, 4, 5, 2],
       [2, 6, 4, 6, 3, 6],
       [8, 7, 2, 0, 1, 8]])

def test(A):
    return np.max(A,axis=0)

print(test(A))

In [0]:
"""
#15
Write a code generating the following ndarray B from a given ndarray A. 

A:
array([[ 9, 16, 15,  3, 17, 14],
       [ 1, 14, 12, 18, 13,  9],
       [ 8, 18,  5, 18,  6,  7],
       [10, 15,  9, 19,  2, 19],
       [ 8,  2, 13, 14, 17, 11],
       [ 3,  7,  2,  5, 15, 11]])


B:
array([[ 0, 16, 15,  0, 17, 14],
       [ 0, 14, 12, 18, 13,  0],
       [ 0, 18,  0, 18,  0,  0],
       [ 0, 15,  0, 19,  0, 19],
       [ 0,  0, 13, 14, 17,  0],
       [ 0,  0,  0,  0, 15,  0]])


A's shape: (6, 6), B's shape: (6, 6) 

Hint: 11
"""
A=np.array([[ 9, 16, 15,  3, 17, 14],
       [ 1, 14, 12, 18, 13,  9],
       [ 8, 18,  5, 18,  6,  7],
       [10, 15,  9, 19,  2, 19],
       [ 8,  2, 13, 14, 17, 11],
       [ 3,  7,  2,  5, 15, 11]])

def test(A):
    return np.where(A<=11,0,A)

print(test(A))